export const APP_VIEW_CHANGE = "APP_VIEW_CHANGE";
export const AUTH_USER_SET = "AUTH_USER_SET";
export const AUTH_USER_LOGOUT = "AUTH_USER_LOGOUT";

export const ADMIN_USERS_GET_ALL = "ADMIN_USERS_GET_ALL";
