export const APP_VIEW_CHANGE = "APP_VIEW_CHANGE";
export const APP_ALERT_CLOSE = "APP_ALERT_CLOSE";

export const AUTH_USER_LOGIN = "AUTH_USER_LOGIN";
export const AUTH_USER_LOGIN_ERROR = "AUTH_USER_LOGIN_ERROR";
export const AUTH_USER_SET = "AUTH_USER_SET";
export const AUTH_USER_LOGOUT = "AUTH_USER_LOGOUT";

export const ADMIN_USERS_FETCH_ALL = "ADMIN_USERS_FETCH_ALL";
export const ADMIN_USERS_GET_ALL = "ADMIN_USERS_GET_ALL";

export const ADMIN_USER_SUBMIT = "ADMIN_USER_SUBMIT";
export const ADMIN_USER_SUBMIT_ERROR = "ADMIN_USER_SUBMIT_ERROR";
export const ADMIN_USER_SUBMIT_SUCCESS = "ADMIN_USER_SUBMIT_SUCCESS";
export const ADMIN_USER_ERRORS_CLEAR = "ADMIN_USER_ERRORS_CLEAR";
